# Generated by Django 5.0.6 on 2024-06-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=25, verbose_name='Артикул поставщика')),
                ('lm_article', models.CharField(max_length=25, verbose_name='Артикул ЛМ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('depth', models.IntegerField(verbose_name='Высота')),
                ('shop', models.CharField(max_length=50, verbose_name='Артикул ЛМ')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('address', models.CharField(max_length=25, verbose_name='Адрес хранения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_photos/')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
