# Generated by Django 5.0.6 on 2024-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Запись в реестр', 'verbose_name_plural': 'Реестр оборудования'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес хранения'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='article',
            field=models.CharField(max_length=250, verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lm_article',
            field=models.CharField(max_length=250, verbose_name='Артикул ЛМ'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='shop',
            field=models.CharField(max_length=500, verbose_name='Магазин'),
        ),
    ]
