# Generated by Django 4.2.13 on 2024-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='shop',
            field=models.CharField(max_length=250, verbose_name='Магазин'),
        ),
    ]
